version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www/
      - ./docker/web/common.conf:/etc/nginx/conf.d/default.conf
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - challenge

  app:
    image: sabido/core:latest
    volumes:
        - ./:/var/www/
        - ./docker/app/custom.php.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
        - mysqldb
    ports:
      - 9912:9912 # xdebug port
    restart: unless-stopped
    networks:
        - challenge

  mysqldb:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - challenge

volumes:
  mysqldb:

networks:
  challenge:
    driver: bridge
    name: challenge
